# Default values for frontend service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
---
replicaCount: 1

image:
  repository: library/apigateway
  tag: latest
  pullPolicy: Never

env:
  BOOKSERVICE: http://backend-booksservice:4000
  CUSTOMERSERVICE: http://backend-customersservice:5000
  ORDERSERVICE: http://backend-ordersservice:6000

envSecrets:

container:
  port: 8000

service:
  type: LoadBalancer
  port: 8000
  loadBalancerSourceRanges:
    - 0.0.0.0/0
  externalIPs: []

ingress:
  create: false

resources:
  limits:
    cpu: 50m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 32Mi

nodeSelector: {}

tolerations: []

affinity: {}
