# Default values for book service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
---
replicaCount: 1

image:
  repository: library/book
  tag: latest
  pullPolicy: Never

env:
  MONGO_HOST: mongodb-local
  MONGO_PORT: 27017
  DB_NAME: Book
  USER_NAME: bookUser

envSecrets:
  PASSWORD: mongodb-book-local

container:
  port: 4000

service:
  type: ClusterIP
  port: 4000
  externalIPs: []

ingress:
  create: false

resources:
  limits:
    cpu: 50m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 32Mi

nodeSelector: {}

tolerations: []

affinity: {}
